name: PR Build Check

on:
  pull_request:
    branches: [ main ]

# Set permissions
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install and build
        uses: withastro/action@v1
        with:
          node-version: 18
          package-manager: pnpm@latest